testing-library/svelte-testing-library

README.md, src/index.js, tests/queries.spec.js
=> feat: spread all of options on component

src/index.js, tests/render.spec.js
hello all :wave:
thank you so much for these bindings! it's been a breeze playing with svelte and now I can do tdd in the same way I do with react!
this pr address the discussion in https://github.com/testing-library/svelte-testing-library/issues/9
=> #9 - add custom container target

src/index.js, tests/render.spec.js
addressing discussion from https://github.com/testing-library/svelte-testing-library/issues/10
=> #10 - clean up document targets and components

src/index.js
The `target` is always appended to the DOM, regardless if the user supplied a `target` option or not. This PR makes it so we don't add it to the body if `target` is set.
=> Don't append target to body if target option is given

package.json
=> fix: Moved dom-testing-library as direct dependency

README.md, package-lock.json, package.json, src/index.js
BREAKING CHANGE svelte-testing-library is now `@testing-library/svelte`
=> feat: renaming package

jest.config.js, package-lock.json, package.json, src/index.js, tests/example/App.html, tests/render.spec.js
This change checks the default property of the `Component` argument in `render` to prevent problems mounting components due to the way that Svelte handles the presence of both named and default imports when compiling to `cjs`.
In order to test this I added another jest transform targetting `.html` files instead of `.svelte` files and used a jest transform that uses `svelte.compile` directly and compiles to `cjs`. An example `App.html` and a test rendering this file was also added.
Fixes #32.
=> Check the default property of `Component` for the constructor

README.md
~apologies for the url name in codesandbox, is auto generated 😅~ I found a way to update it :P
fixes #42 and #43
=> feat: fix README demo + live demo in CodeSandbox with Tests

src/index.js, tests/act.spec.js
Adds a function which can wrap testing actions and guarantees that after awaited state updates are flushed to the DOM.
Internal it just calls the callback and returns the promise from svelte's [`tick`](https://svelte.dev/docs#tick). This should replace the current documented approach of using `wait` + `expect` or `waitForElement`. The previous behavior either waited too long (default timeout of 2s) or was flaky if the timeout was really short. It's also slow when using `wait` since that uses polling.
It essentially mimics the [`act` from React](https://reactjs.org/docs/test-utils.html#act).
=> feat: Add act

README.md
I am junior in Svelte and completely not sure, that its example should be fixed at all. But Jest ESLint plugin has [recommended rule](https://github.com/jest-community/eslint-plugin-jest/blob/master/docs/rules/valid-expect.md) to show error on any `expect()` without matcher after it.
Should we add explicit matcher here? (Even if library hack `expect` we still need matcher for ESLint plugin)
=> Fix example in the docs

src/pure.js
This is mostly in reference to #57. There are some use cases for testing with the component directly such as exported functions. The docs have also been updated accordingly.
=> style: remove warning comment above component from rendered results

types/index.d.ts
Following up on https://github.com/sveltejs/svelte/issues/3892
* this correlates to [`pure.js`](https://github.com/testing-library/svelte-testing-library/blob/master/src/pure.js#L8) behaviour
=> fix(types): use exported SvelteComponent

package.json, src/__tests__/__snapshots__/render.test.js.snap, src/__tests__/render.test.js, src/pure.js
=> feat: allow easier passing in of props

src/__tests__/render.test.js, src/pure.js
=> feat: throw error when mixing props and svelte options

.eslintrc.js, src/pure.js
=> fix: eslint error and rerender issue that wouldn't use props

src/__tests__/__snapshots__/auto-cleanup-skip.test.js.snap, src/__tests__/__snapshots__/render.test.js.snap, src/__tests__/fixtures/Comp.svelte, src/__tests__/render.test.js, src/pure.js
For #136
Allows 'context' as one of the Svelte options.
Note that most of the changes are due to prettier and husky. (I pushed a new version with husky disabled, because the signal to noise ratio was just too bad. If the PR makes sense we can always prettierify it after the fact)
=> feat: add context to the allowed options

package.json
Also tests on Node 14 and 16. IMO this isn't a breaking change, since Node 8 was already broken because of our DOM Testing Library version using newer syntax.
=> fix: update incorrect Node version requirement from 8 to 10

types/index.d.ts
A straight-up revert of index.d.ts to v3.1.1.
=> fix: revert breaking type change

types/index.d.ts
Proposal that enable typing of Svelte component properties using the `render` function.
=> feat: improve props typing for `render` function

types/index.d.ts
Fixing the previous merged proposal: https://github.com/testing-library/svelte-testing-library/pull/202. `Constructor<T>` constraint was applied only to one of the two signatures of the `render()` function.
=> fix: missing Constructor constraint to first render() type signature

package.json
closes https://github.com/testing-library/svelte-testing-library/issues/223
=> chore: Add Svelte 4 as supported version

package.json, types/index.d.ts
The `exports` map in `package.json` was missing it's `types` module path, causing the import of `@testing-library/svelte` to throw a type error whenever users had `"moduleResolution": "nodenext"` set in their `tsconfig.json`.
=> fix: added module path for `types` to the `exports` map

package.json
Hi there, I'm having issues with type resolution after updating from 3.2.2 to 4.0.2. I ran it through publint, which states the `exports` field needs to list `types` before everything else: https://publint.dev/@testing-library/svelte@4.0.2
=> fix: Update package.json exports order

types/index.d.ts
The implementation of `act()` requires a function, but the type annotation says it takes either a function or a Promise.
After checking out the history, I found this mismatch was created by #54, which added both the type annotation and implementation for `act`. This leads me to think the best path forward now is to simply adjust the type annotation to match reality, rather than updating the implementation to support a Promise.
Closes #134
=> fix(types): correct type annotation for `act`

src/pure.js
@mcous Your #288 made me look at the implementation of `act()`, and I think it can be simplified as per this PR.
=> chore: simplify implementation of act

.eslintrc.cjs, .husky/commit-msg, .husky/pre-commit, .prettierrc.yaml, package.json, types/index.d.ts, vite.config.js
This PR fixes some code quality configs and hookups that we making it difficult to contribute effectively to this project.
Part of a two PR change set:
1. #291 **<-- you are here**
2. #292
- Incorporate `eslint-plugin-svelte`, `@typescript-eslint/eslint-plugin`, `eslint-plugin-prettier` into the ESLint config to:
- Lint `.svelte` files
- Lint `.d.ts` files
- Avoid conflicts with prettier
- Migrate the Husky config [to v8](https://typicode.github.io/husky/migrating-from-v4.html)
- Fix up the `lint-staged` config now that Husky is actually working
(On a personal note, I'm not a huge fan of pre-commit hooks anymore. I find they interfere with people's personal work styles, and they're pretty unnecessary in a PR-squashing-based workflow. **I'd be down to ditch the pre-commit stuff from the …
=> chore: fix linting, formatting, and git hooks configs

.github/workflows/release.yml, package.json
This is the second PR in a series to add multiple Svelte versions and test runners to our CI test matrix.
1. #294 
2. #295 **<-- you are here**
3. #297
4. TODO add Jest to CI matrix
This PR updates the CI test matrix to install different Svelte versions prior to testing
- Replace third party action with `npm install` for flexibility and security
- Call `npm install svelte` with a specific version in CI from the matrix
- Update action dependencies to remove CI warnings
- `cycjimmy/semantic-release-action` needs an update too, but I'd like to leave release stuff to its own PR in case of issues
=> ci: test against svelte v3 and v4

.github/semantic.yml, .husky/commit-msg, .husky/pre-commit, package.json
Husky, lint-staged, and commitlint all add heavy-handed constraints to local development that don't make a lot of sense in a world where:
- CI is fast because this project is small and will remain small
- Pull-requests are squash merged
- Pull-request titles are checked via CI
Relates to #299, which adds contributing documentation.
Closes #293.
=> chore: remove husky, lint-staged, and commitlint

package.json, src/__tests__/fixtures/Transitioner.svelte, src/__tests__/transition.test.js
This PR adds a test for `on:introend`, using suggestions from the #206 thread, for ensuring that [transition events][] can be tested.
Closes #206
[transition events]:
https://svelte.dev/docs/element-directives#transition-events
- Add `on:introend` test
- Stub out `requestAnimationFrame` in transition test when on jsdom
Weirdly enough, without the stub, in jsdom the test passes the first time in watch mode and fails all subsequent times. Smells like maybe some sort of bug in jsdom or Vitest, but I didn't investigate further
=> test(transitions): add `on:introend` test

.github/dependabot.yml, .github/workflows/lint-pr.yml
Very minor updates and cleanup to address deprecation warnings currently happening in CI. Had this lying around locally, mostly just want to get it out of my queue
=> ci: update semantic-pull-request and cleanup dependabot

.github/workflows/release.yml
Had a spare moment and this seemed helpful. Don't have any personal preferences on the branch name, but `next` felt easy because it was already configured and matches Svelte itself, which is currently publishing v5 on its `next` dist-tag in npm
=> ci: run release workflow on `next` branch

.github/workflows/release.yml, package.json, src/__tests__/__snapshots__/render.test.js.snap, src/__tests__/cleanup.test.js, src/__tests__/fixtures/Mounter.svelte, src/__tests__/fixtures/Rerender.svelte, src/__tests__/mount.test.js, src/__tests__/render.test.js, src/__tests__/rerender.test.js, src/__tests__/transition.test.js, src/pure.js, types/index.d.ts, vite.config.js
This PR is an alternative approach to #284 (CC @yanick) that adds experimental support for `svelte@next` without breaking support for Svelte v3 nor v4. I think adding support for the prerelease version of Svelte v5  as soon as possible will be a really helpful move for everyone trying to migrate - myself very much included.
This PR requires the cleanup work I did in #314. Please see https://github.com/mcous/svelte-testing-library/pull/1 in my fork for the incremental diff from #314 to here. This PR is ready for review, but #314 should merge first
- `onMount` and `onDestroy` are attached and called asynchronously
- If you synchronously create and then destroy a component, neither `onMount` nor `onDestroy` will be called
- Tests required a sprinkling of `act()`s to get passing again
- …
=> feat: add Svelte v5-next support

.eslintrc.cjs, .prettierignore, .prettierrc.yaml, src/__tests__/act.test.js, src/__tests__/auto-cleanup.test.js, src/__tests__/cleanup.test.js, src/__tests__/context.test.js, src/__tests__/debug.test.js, src/__tests__/events.test.js, src/__tests__/fixtures/Comp.svelte, src/__tests__/fixtures/Context.svelte, src/__tests__/mount.test.js, src/__tests__/render.test.js, src/__tests__/rerender.test.js, src/__tests__/transition.test.js, src/vitest.js, svelte.config.js
This PR follows up the option cleanup of #325 with some test cleanup.
- Remove an unnecessary cleanup test skip
- Remove a redundant `fireEvent` test
- Ensure `IS_SVELTE_5` from util is used in tests
- Align `console` mocks for consistency
- Replace `new Promise` for sleep with [`node:timers/promises`](https://nodejs.org/api/timers.html#timers-promises-api)
- Sort imports in tests when my editor yelled at me
=> test: remove unnecessary tests and skips

src/__tests__/events.test.js, src/index.js, src/svelte5-index.js, vite.config.js
#328 moved exports from `pure.js` to `index.js` and switched everything to wildcard exports:
https://github.com/testing-library/svelte-testing-library/blob/0593819ca0e083eadf536d20d9d61944d594fb91/src/index.js#L15-L16
If two wildcard exports emit the same export, [neither will be included](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/export). 
> There is also `export * from "mod"`, although there's no `import * from "mod"`. This re-exports all named exports from `mod` as the named exports of the current module, but the default export of `mod` is not re-exported. If there are two wildcard exports statements that implicitly re-export the same name, **neither one is re-exported**.
**This means the current release on `next` is not exporting `fireEvent`**. This …
=> fix: ensure fireEvent is exported

.github/workflows/release.yml
This PR adds a scheduled event to CI to run the `main` job in the `release.yml` workflow weekly. Since the workflow always downloads the latest tagged version of the Svelte version under test, this should alert us of any breaks due to upstream changes
=> ci: run weekly check with latest svelte versions

package.json, src/__tests__/context.test.js, src/__tests__/mount.test.js
Remove test skips now that https://github.com/capricorn86/happy-dom/pull/1393 has landed. Our Svelte 5 + happy-dom suite is now fully passing without any happy-dom specific skips
Closes #319
=> test: remove Svelte 5 + HappyDOM skips after bugfix

src/svelte5-index.js
Fix the issue noted in #342. Closely related to the issues fixed by #339, but I missed that that `act` was also wrong, because our own test suite does not trigger the auto-cleanup behavior
=> fix(svelte5): ensure proper `act` used in cleanup

package.json, vite.config.js
Verifying that our test suite functions normally without us having to disable HMR ourselves with sveltejs/vite-plugin-svelte#913
=> chore(deps): update vite-plugin-svelte to disable `hmr` in test

.github/workflows/release.yml, CONTRIBUTING.md, package.json, release.config.js, scripts/preview-release
This PR updates the semantic-release configuration for several maintenance improvements and simplifications.
Merging this PR into `next` just in case there are any issues
- Use the `conventionalcommits` preset for version detection and changelog generations (closes #354)
- Add a simple `preview-release` script for maintainers (closes #356)
- Change `next` to a prerelease branch, remove other non-`main` branch configurations because we don't use them
=> ci(release): use conventionalcommits preset for release

README.md
Nothing much to see here, just pruning dead links from the README and moving anchor labels to the sections where they are actually used
=> docs(README): move links to sections that use them, remove unused links

jest.config.js, vite.config.js
Coverage stats are a little off since fixing the codecov uploads. This PR fixes them up and aligns Jest and Vitest to collect from the same source files
=> test(coverage): ensure proper files are included/excluded

src/__tests__/mount.test.js, src/core/modern.svelte.js
Svelte 5 tests started failing in the mount/unmount tests. This PR adds a `flushSync` call to mount / unmount to ensure that components behave as users expect in a testing environment
=> fix(svelte5): synchronously flush changes after mount and unmount

.github/workflows/release.yml, package.json, src/__tests__/fixtures/Mounter.svelte, src/__tests__/fixtures/Typed.svelte, src/__tests__/fixtures/TypedRunes.svelte, src/__tests__/render-runes.test-d.ts, src/__tests__/render-utilities.test-d.ts, src/__tests__/render.test-d.ts, src/component-types.d.ts, src/pure.js, tsconfig.legacy.json
Resolves the typing issue highlighted in https://github.com/testing-library/svelte-testing-library/issues/284#issuecomment-2381405022
=> fix(svelte5): update typings to support new component types

package.json, src/component-types.d.ts
Made a silly mistake with #400 that meant the new typings weren't actually included in the published module. This PR fixes that mistake
=> fix(svelte5): ensure typings are actually included in the module

src/__tests__/utils.js, src/__tests__/vite-plugin.test.js, src/vite.js, vite.config.js
If `@testing-library/svelte` is not set in the `package.json` of the project Vitest is running in (e.g. in certain monorepo setups), `@sveltejs/vite-plugin-svelte` will not detect that it needs to be inlined. This, in turn, breaks Svelte 5 support, which relies on STL running through the Svelte compiler for runes support.
Hopefully this is something that can be fixed in `@sveltejs/vite-plugin-svelte`, but it might not be! This PR updates our own Vite plugin to ensure this setting is correct, even if `@sveltejs/vite-plugin-svelte` misses it.
Fixes #403
=> fix(vite): set `ssr.noExternal` even if not in project package.json

.github/workflows/release.yml, package.json, scripts/install-dependencies
Now that Svelte 5 is released on the `latest` tag, this PR updates `package.json` and the CI config to use Svelte 5 by default
- Bump default dev environment to Svelte 5
- Improve dependency installation for older Svelte versions in CI
- Enable type-checking on Svelte 3 in CI (enabled by better dependency installations)
=> ci: use production release of Svelte 5 by default

.eslintrc.cjs, src/__tests__/render.test-d.ts, src/component-types.d.ts
When using `@testing-library/svelte@5.2.x` with Svelte 4, wrapping `render` can cause spurious `@typescript-eslint/no-unsafe-argument` errors. I suspect this is due to some sort of bug in `eslint-plugin-svelte`, but I have not yet produced a minimal reproduction.
```ts
import type { ComponentProps } from 'svelte';
import { render } from '@testing-library/svelte';
import Subject from '../app.svelte';
const renderSubject = (props: ComponentProps<Subject>) => {
return render(Subject, props);
};
```
```
error  Unsafe argument of type `any` assigned to a parameter of type `SvelteComponentOptions<SvelteComponent<Record<string, any>, Record<string, any>, Record<string, any>>> | undefined`  @typescript-eslint/no-unsafe-argument
```
In the meantime, this PR
- Adjusts the types so that ESLint does …
=> fix(types): adjust legacy types for eslint-plugin-svelte

.github/workflows/release.yml, .gitignore, CONTRIBUTING.md, package.json, src/__tests__/render.test-d.ts, src/component-types.d.ts
Continuing type annotation fixes from #409 - the existing built types erase the `Component` type constraint on the first argument to `render`, causing fun issues - including but not limited to `@typescript-eslint` errors.
This PR fixes the issue and adds a failing type test
=> fix(types): do not erase component type constraint

src/__tests__/auto-cleanup.test.js
The update to `esm-env@2` from sveltejs/svelte#14460 caused our auto-cleanup tests in Jest to start failing on Svelte's internal runes environment check heuristic.
```
FAIL  src/__tests__/auto-cleanup.test.js
● auto-cleanup › calls afterEach with cleanup if globally defined
Svelte error: rune_outside_svelte
The `$state` rune is only available inside `.svelte` and `.svelte.js/ts` files
```
I'm not entirely sure of the failure mechanism, but there's a definite difference in what `esm-env` reports in Jest+JSDOM in `v1` vs `v2`. That being said, the auto-cleanup tests use mock functions, reseting the module cache, and faking out `process.env`. On top of that, Jest's ESM support is still experimental. There's a high chance there are shenanigans that have nothing to do with `esm-env` and/or …
=> test(jest): skip auto-cleanup tests in Jest

src/__tests__/fixtures/Typed.svelte, src/__tests__/render-runes.test-d.ts, src/component-types.d.ts
Uncovered two issues with the `render` return types when using Svelte 5 with legacy (non-runes) components:
- The `render` function should accept `events` as an option
- The returned `component` should not have `$set`, `$on`, nor `$destroy` methods, which will error at runtime
=> fix(types): fix types when using legacy components in Svelte 5

package.json, src/__tests__/render-runes.test-d.ts, src/__tests__/render-utilities.test-d.ts, src/__tests__/render.test-d.ts, tsconfig.json
Test-only change, good to merge if CI agrees. Also added `typescript-svelte-plugin` to `tsconfig.json` for better Zed editor support
=> test: replace deprecated `toMatchTypeOf`

.github/workflows/release.yml
CI only change, good to merge if CI is green
=> ci: expand matrix to include Node 22

README.md, jest.config.js, src/index.js, src/pure.js, src/vitest.js, tests/_jest-setup.js, tests/_jest-vitest-alias.js, tests/act.test.js, tests/auto-cleanup.test.js, tests/events.test.js
While working on new examples for Svelte 5, I found a problem with this library's interop with `@testing-library/user-event` - depending on project setup, `await user.click()` et. al. does not wait for Svelte to flush changes.
We were missing a call to `configure` to `@testing-library/dom` to configure the `eventWrapper` (for `fireEvent`) and `asyncWrapper` (for `user-event`) options. This fixes the issue for `user-event`, and happily, removes the need for an async re-export of `fireEvent` once we're able to drop Svelte 3/4, thanks to the new `flushSync` export from `svelte`
Related (old) issue: #250
- Add `setup` function to complement `cleanup` function that calls `@testing-library/dom::configure` with `tick` and `flushSync`
- Wire `setup` into `beforeEach` for Jest and Vitest
- Add …
=> fix: configure dom-testing-library to flush Svelte changes
